config/routes.rb
# This file is a part of Redmine Checklists (redmine_checklists) plugin,
# issue checklists management plugin for Redmine
#
# Copyright (C) 2011-2014 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_checklists is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_checklists is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_checklists.  If not, see <http://www.gnu.org/licenses/>.

RedmineApp::Application.routes.draw do
  match '/projects/:project_id/checklist/settings',:to => 'checklist_config#update', :via => :put,:as => 'checklist_config'
    
end

resources :issues do
  resources :checklists, :only => [:index, :create]
end

resources :checklists, :only => [:destroy, :update, :show] do
  member do
    put :done
  end
end

app/controllers/checklist_config_controller.rb
class ChecklistConfigController < ApplicationController
  unloadable

  before_filter :find_project_by_project_id, :authorize
  
  accept_api_auth :index, :update, :destroy, :create, :show
  
  def index
    @project_checklists = @project.project_checklists
    respond_to do |format|
      format.api
    end
  end
  
  def show
    respond_to do |format|
      format.api
    end
  end
  
  def destroy
    @project_checklist_item.destroy
    respond_to do |format|
      format.api {render_api_ok}
    end
  end
  
  def create
    
  end
  
  def update
    tracker = params[:tracker]
    if params[:project] !=nil
      checklists = params[:project][:project_checklists_attributes] 
      checklists.each do |key,param|
        param[:tracker_id] = tracker
        @project.checklist_tracker_id = tracker
        @project.project_checklists_attributes = param
        @project.save
      end
    end
    redirect_to :controller => 'projects',:action => "settings", :id => @project, :tracker => tracker, :tab => 'checklist'
  end
  
  private
  def find_project_checklist_item
    @project_checklist_item = ProjectChecklist.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/checklist_config_helper.rb
module ChecklistConfigHelper
  def link_to_remove_checklist_fields(name, f, options={})
    f.hidden_field(:_destroy) + link_to(name, "javascript:void(0)", options)
  end

  def new_object(f, association)
    @new_object ||= f.object.class.reflect_on_association(association).klass.new
  end

  def fields(f, association)
    @fields ||= f.fields_for(association, new_object(f, association), :child_index => "new_#{association}") do |builder|
      render("checklist_config/" + association.to_s.singularize + "_fields", :f => builder)
    end
  end

  def new_or_show(f)
    if f.object.new_record?
      if f.object.subject.present?
        "show"
      else
        "new"
      end
    else
      "show"
    end
  end

  def done_css(f)
    if f.object.is_done
      "is-done-checklist-item"
    else
      ""
    end
  end
end

app/views/checklist_config/_checklist_fields.html.erb
<span class="checklist-item <%= new_or_show(f) %>" id = "<%=f.object.id%>">
  <span class = "checklist-show-only checklist-checkbox"><%= f.check_box :is_done %></span>
  <span class = "checklist-show checklist-subject <%= done_css(f) %>">
    <%= f.object.subject %>
  </span>
  <span class = "checklist-edit checklist-new checklist-edit-box">
    <%= text_field_tag nil, f.object.subject, :class => 'edit-box'%>
    <%= f.hidden_field :subject, :class => 'checklist-subject-hidden' %>
  </span>
  <span class= "checklist-edit-only checklist-edit-save-button"><%= submit_tag l(:button_save), :type => "button",
                                                                      :class => "item item-save"%> </span>
  <span class= "checklist-edit-only checklist-edit-reset-button"><% concat l(:button_cancel)
  %> </span>
  <span class = "checklist-show-only checklist-remove"><%= link_to_remove_checklist_fields "", f,
                                                                            :class => "icon icon-del"  %></span>
  <%= f.hidden_field :position, :class => 'checklist-item-position' %>
  <%= f.hidden_field :id, :class => 'checklist-item-id' %>
  <span class = "icon icon-add checklist-new-only save-new-by-button"></span>

 <br>
</span>

app/views/checklist_config/_create.html.erb
<% if User.current.allowed_to?(:create_checklists, @project) %>
<% if @project.trackers.blank?
      flash[:error] = l(:error_no_tracker_in_project)
 else
 %>
    
<% @project.checklist_tracker_id = params[:tracker].nil? ? @project.trackers.first.id : params[:tracker] %>
<%= form_tag(checklist_config_url(@project), :method => 'put',:id => 'checklist-form') do %>
<fieldset class="box tabular">
  	<legend><%= l(:label_checklist_default) %>:</legend>
 <div class="tabular">
  <p id="checklist_tracker">
  	<label for ="tracker"><%=l(:label_tracker)%></label>
  	<%= select_tag "tracker", options_from_collection_for_select(@project.trackers, "id", "name",@project.checklist_tracker_id.to_i), :onchange => 'checklist_tracker()'%>
  </p>
  <p id="checklist_form">
    <label><%=l(:label_checklist_plural)%></label>
		<% @project.project_checklists.build if @project.project_checklists.blank? || @project.project_checklists.last.subject.present? %>
	  <%= fields_for :project,@project do |f| -%>
	    	<span id="checklist_form_items" data-checklist-fields='<%= fields(f, :project_checklists) %>'>
			  <%= f.fields_for :project_checklists do |builder| %>
				<%= render :partial => 'checklist_config/project_checklist_fields', :locals => {:f => builder, :project_checklist => @project_checklist} %>
			  <% end %>
      		</span>
		<% end %>
  </p>
</div>
 </fieldset>
 <%= submit_tag l(:button_save) %>
<% end %>
<% content_for :header_tags do %>
    <%= javascript_include_tag :project_checklists, :plugin => 'redmine_checklists'  %>
    <%= stylesheet_link_tag :checklists, :plugin => 'redmine_checklists'  %>
<% end %>
<% end %>
<%end%>

app/views/checklist_config/_project_checklist_fields.html.erb
<span class="checklist-item <%= new_or_show(f) %>" id = "<%=f.object.id%>">
  <span class = "checklist-show-only checklist-checkbox"><%= f.check_box :is_done %></span>
  <span class = "checklist-show checklist-subject <%= done_css(f) %>">
    <%= f.object.subject %>
  </span>
  <span class = "checklist-edit checklist-new checklist-edit-box">
    <%= text_field_tag nil, f.object.subject, :class => 'edit-box'%>
    <%= f.hidden_field :subject, :class => 'checklist-subject-hidden' %>
  </span>
  <span class= "checklist-edit-only checklist-edit-save-button"><%= submit_tag l(:button_save), :type => "button",
                                                                      :class => "item item-save"%> </span>
  <span class= "checklist-edit-only checklist-edit-reset-button"><% concat l(:button_cancel)
  %> </span>
  <span class = "checklist-show-only checklist-remove"><%= link_to_remove_checklist_fields "", f,
                                                                            :class => "icon icon-del"  %></span>
  <%= f.hidden_field :position, :class => 'checklist-item-position' %>
  <%= f.hidden_field :id, :class => 'checklist-item-id' %>
  <span class = "icon icon-add checklist-new-only save-new-by-button"></span>

 <br>
</span>

app/views/checklist_config/update.html.erb
<h2>ChecklistConfigController#update</h2>